openapi: 3.0.1
info:
  title: App
  description: >-
      This documentation is created for tutorial purposes.  
  contact:
    email: khanim97@gmail.com 
  version: 'v1.0'
externalDocs:
  description: Github Repository 
  url: https://github.com/Shervin1995/app
paths:


# -------------------------
# category
# -------------------------

  /categories:
    get:
      tags:
        - Category 
      description: Get list of categories.    
      
      responses:
      
        '200':
          description: Get List Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category' 
                  
        '500':
          description: Internal Error from DB.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
  
  /add-category:
    post:
      tags:
        - Category 
      description: Add to category! 
      
      
      parameters:
      
        - name: title
          in: query
          description: Title of category
          required: true 
          schema:
            type: string 
              
              
      responses:
        '200':
          description: Added Successfully
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Error from DB.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
  
       
# -------------------------
# product
# -------------------------

  /products:
    get:
      tags:
        - Product 
      description: Get list of products.   
      
      responses:
        '200':
          description: Get List Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product' 
        '500':
          description: Internal Error from DB.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
                
  
  /add-product:
    post:
      tags:
        - Product 
      description: add to products! 
      
      
      parameters:
      
        - name: name
          in: query 
          required: true 
          schema:
            type: string 
        
        - name: categoryID
          in: query
          required: true
          schema: 
            $ref: '#/components/schemas/Category/properties/id'
              
              
      responses:
      
        '200':
          description: Added Successfully
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Error from DB.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
 
 
  /update-product:
    post:
      tags:
        - Product 
      description: update the product! 
      
      
      parameters:
      
        - name: name
          in: query 
          required: true 
          schema:
            type: string 
        
        - name: theID
          in: query
          required: true
          schema: 
            $ref: '#/components/schemas/Product/properties/id'
              
              
      responses:
      
        '200':
          description: Added Successfully
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
                
        '500':
          description: Internal Error from DB.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
                 

  /delete-product:
    delete:
      tags:
        - Product 
      description: delete from products! 
      
      
      parameters:
       
        - name: theID
          in: query
          required: true
          schema: 
            $ref: '#/components/schemas/Product/properties/id'
              
              
      responses:
      
        '200':
          description: deleted Successfully
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Error from DB.
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ErrorMessage'
      
# -------------------------
# schema
# -------------------------
               
                
components:
  schemas: 
  
    Category:
      type: object    
      properties:  
        id:
          type: integer  
        title:
          type: string
          
          
    Product:
      type: object    
      properties:  
        id:
          type: integer 
        name:
          type: string
        categoryID: 
          $ref: '#/components/schemas/Category/properties/id'
          
          
    ErrorMessage:
      type: object    
      properties:  
        message:
          type: string 



